{{- if .Values.global.workloadIdentity.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.global.workloadIdentity.secretProviderClassName }}
  labels:
    {{- include "three-tier-app.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.global.database.secretName }}
      type: Opaque
      data:
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: db-name
          key: DB_NAME
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.global.workloadIdentity.clientId | quote }}
    keyvaultName: {{ .Values.global.workloadIdentity.keyVaultName | quote }}
    tenantId: {{ .Values.global.workloadIdentity.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
{{- end }}
